### PR TITLE
Prevent Network Errors on switch chain

### LINKED ISSUE #335: Intercept network changes to avoid errors
When the user's wallet is switched away from the correct network (set by env variable REACT_APP_NETWORK_ID), the app still tries to call methods on the SDK which causes network errors. 

Instead, we should prevent the app from calling SDK, and show the banner warning the user they are on the wrong network.

geb initialization could be used to stop attempting to call the SDK if the app is on the wrong network.

### PR DESCRIPTION
**Pull request by Seroxdesign**
closes #335 

A few issues surfaced in this PR:

1. Typing for Geb was not correct, Network should be GebDeployment
2. There were no checks to see if the network switched to are supported prior to triggering functions
3. Too many functions are being triggered when geb changes
4. The Network error warning did not disappear after switching to correct chain

Additionally I noticed the overuse of the useEffect hook:
https://react.dev/learn/you-might-not-need-an-effect

Cleaning that up can come later, but 9 in 1 file is too much, and there too many hooks which are copy pasted in multiple files.

### CODE REVIEW

File: src/containers/Vaults/index.tsx [hunk 1]
```diff
@@ -24,6 +24,7 @@ const OnBoarding = ({ ...props }) => {
     const address: string = props.match.params.address ?? ''
 
     useEffect(() => {
+        if (chainId !== 421614 && chainId !== 42161 && chainId !== 10) return
```
Comment (pi0neerpat) [inline src/containers/Vaults/index.tsx:27]: Can you double check this works as expected? Seems like it will never be true?

**Review by pi0neerpat — APPROVED** [review]
