### PR TITLE
Issue #304: Fix Styled Components not Inheriting React Props

### LINKED ISSUE #304: Fixed Styled Components IDE Error
Fix errors causing styled components to not inherent base React props.

image

### PR DESCRIPTION
**Pull request by kai-thompson**
closes #304 

Changes:
- update react types dependancy to match current react version used in app
- regenerate yarn.lock
- remove tsconfig.json setting causing error
- fixed misc. type errors
- updated easy-peasy dependency to ^5.1.0 to be compatible with react-18 types https://github.com/ctrlplusb/easy-peasy/issues/741

### CODE REVIEW

File: src/containers/Vaults/VaultDetails.tsx [hunk 1]
```diff
@@ -103,7 +103,7 @@ const VaultDetails = ({ ...props }) => {
         return () => {
             safeActions.setSingleSafe(null)
         }
-    }, [safe, safeActions, geb, liquidationData, safeActions.liquidationData])
+    }, [safe, safeActions, geb, liquidationData, safeActions.setLiquidationData])
```
Comment (pi0neerpat) [inline src/containers/Vaults/VaultDetails.tsx:106]: Please provide the reason for this change

**Review by pi0neerpat — APPROVED** [review]

File: src/containers/Vaults/VaultDetails.tsx (hunk 1 above)
Comment (kai-thompson) [reply src/containers/Vaults/VaultDetails.tsx:107]: The liqduidationData field isn't a member of the safeActions object so it was throwing a type error. Not sure why it wasn't surfacing before.
I can change it to safeState.liquidationData if that was the intended behaviour. 

image

**Review by jahabeebs — APPROVED** [review]
