### PR TITLE
Global stability fee is incorrect

### LINKED ISSUE #321: Global stability fee is incorrect
image

- [x] remove global stability fee

- [x] Lets move the rates down to the prices section and remove the "Annual Stability Fee" section 

image

- [ ] Remove borrow rate. this is global stability fee + collateral-specific stability fee. 

image

### PR DESCRIPTION
**Pull request by alekseevaiana**
Closes #321 
- Removed Annual Stability Fee
- Moved Redemption Rates to Price
- Removed column Borrow rate

Screenshot 2024-04-05 at 1 14 46 PM

Screenshot 2024-04-05 at 2 08 02 PM

### CODE REVIEW

File: src/containers/Analytics/DataTable.tsx [hunk 1]
```diff
@@ -35,8 +35,12 @@ export const DataTable = ({ title, colums, rows }: TableProps) => {
                                 {item?.map((value, valueIndex) => (
```
Comment (pi0neerpat) [inline src/containers/Analytics/DataTable.tsx:35]: Can you add logic here to skip the item in the list? Or remove the item from the list prior to this mapping

**Review by pi0neerpat — CHANGES_REQUESTED** [review]

File: src/containers/Analytics/DataTable.tsx (hunk 1 above)
Comment (alekseevaiana) [reply src/containers/Analytics/DataTable.tsx]: I've skipped item with index 6, but I don't like this solution. I can dig dipper, or can leave it like this.

Comment (alekseevaiana) [reply src/containers/Analytics/DataTable.tsx]: Found where it comes from. So I removed it from fetching
```
const colRows = Object.fromEntries(
                        Object.entries(analyticsData?.tokenAnalyticsData).map(([key, value]) => {
                            const lockedAmountInUsd = multiplyWad(
                                value?.lockedAmount?.toString(),
                                value?.currentPrice?.toString()
                            )
                            totalLockedValue = totalLockedValue.add(lockedAmountInUsd)

                            return [
                                key,
                                [
                                    key,
                                    <AddressLink address={geb.tokenList[key].address} chainId={chainId || 420} />,
                                    <AddressLink address={value?.delayedOracle} chainId={chainId || 420} />,
                                    formatDataNumber(value?.currentPrice?.toString() || '0', 18, 2, true),
                                    formatDataNumber(value?.nextPrice?.toString() || '0', 18, 2, true),
                                    transformToAnnualRate(
                                        multiplyRates(
                                            value?.stabilityFee?.toString(),
                                            analyticsData.redemptionRate?.toString()
                                        ) || '0',
                                        27
                                    ),
                                    formatDataNumber(value?.debtAmount?.toString() || '0', 18, 2, true, true),
                                    transformToWadPercentage(
                                        value?.debtAmount?.toString(),
                                        value?.debtCeiling?.toString()
                                    ),
                                    formatDataNumber(value?.lockedAmount?.toString() || '0', 18, 2, false, true) +
                                        ' ' +
                                        key,
                                    formatDataNumber(
                                        multiplyWad(value?.lockedAmount?.toString(), value?.currentPrice?.toString()) ||
                                            '0',
                                        18,
                                        2,
                                        true,
                                        true
                                    ),
                                    transformToWadPercentage(
                                        multiplyWad(
                                            value?.debtAmount?.toString(),
                                            analyticsData?.redemptionPrice?.toString()
                                        ),
                                        multiplyWad(value?.lockedAmount?.toString(), value?.currentPrice?.toString())
                                    ),
                                ],
                            ]
                        })
                    )
```

**Review by pi0neerpat — APPROVED** [review]
